

const company = [
  {
    name: "snow business center",
    startDate: "1990",
    endDate: "2021",
    category:"technology",
  },
  {
    name: "snow business 2",
    startDate: "2008",
    endDate: "2011",
    category:"Finance",
  },
  {
    name: "snow business 3",
    startDate: "1980",
    endDate: "2001",
    category:"carwash",
  },
  {
    name: "snow business 4",
    startDate: "1990",
    endDate: "2021",
    category:"gas station",
  },
  {
    name: "snow business5",
    startDate: "1980",
    endDate: "1987",
    category:"auto dealers",
  },
  {
    name: "snow business6",
    startDate: "1996",
    endDate: "2020",
    category:"carpenter",
  },
  {
    name: "snow business7",
    startDate: "1999",
    endDate: "2022",
    category:"Finance",
  },
  {
    name: "snow business8",
    startDate: "1990",
    endDate: "2017",
    category:"carpenter",
  },
  {
    name: "snow business9 ",
    startDate: "2016",
    endDate: "2021",
    category:"retail",
  },
  {
    name: "snow business10 ",
    startDate: "2001",
    endDate: "2021",
    category:"technology",
  },
  {
    name: "snow enterprise1 ",
    startDate: "1990",
    endDate: "2017",
    category:"car dealer",
  },
  {
    name: "snow enterprise2",
    startDate: "1990",
    endDate: "2014",
    category:"Finance",
  },
  {
    name: "snow enterprise3 ",
    startDate: "2018",
    endDate: "2018",
    category:"retail",
  },
  {
    name: "snow enterprise4 ",
    startDate: "1995",
    endDate: "2019",
    category:"motocycle dealer",
  },
  {
    name: "snow enterprise5 ",
    startDate: "2021",
    endDate: "2022",
    category:"detail and carwash",
  },
  {
    name: "snow enterprise ",
    startDate: "1990",
    endDate: "2024",
    category:"technology",
  },
  {
    name: "snow enterprise ",
    startDate: "2004",
    endDate: "2021",
    category:"auto accessories",
  },
  {
    name: "snow enterprise ",
    startDate: "1990",
    endDate: "2002",
    category:"applliance repair service",
  },
  {
    name: "snow enterprise ",
    startDate: "2016",
    endDate: "2017",
    category:" auto accessories",
  },
  {
    name: "snow enterprise ",
    startDate: "2005",
    endDate: "2021",
    category:"carpenter",
  },
  {
    name: "snow enterprise ",
    startDate: "1979",
    endDate: "1980",
    category:"contractor",
  },
  {
    name: "snow enterprise ",
    startDate: "1975",
    endDate: "2021",
    category:"gas station",
  },
  {
    name: "snow enterprise ",
    startDate: "1995",
    endDate: "1996",
    category:"gas station",
  },
  {
    name: "snow enterprise ",
    startDate: "1990",
    endDate: "2013",
    category:"electrician",
  },
  {
    name: "snow enterprise 6",
    startDate: "2010",
    endDate: "2012",
    category:"Finance",
  },
  {
    name: "snow enterprise 7",
    startDate: "1986",
    endDate: "2021",
    category:"motocycle dealers",
  },
  {
    name: "snow enterprise 8",
    startDate: "1999",
    endDate: "2021",
    category:"finance",
  },
  {
    name: "snow enterprise9 ",
    startDate: "1980",
    endDate: "2006",
    category:"technology",
  },
  {
    name: "snow enterprise30",
    startDate: "1980",
    endDate: "2000",
    category:"gas station",
  },
  {
    name: "snow enterprise30",
    startDate: "1990",
    endDate: "1992",
    category:"auto",
  },
];
console.log(company);